<?php

namespace Cookbook\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRecipeRepository extends EntityRepository
{
     private $custom_value;

    public function __construct($custom_value) {
        $this->custom_value = $custom_value;
    }

}