<?php

namespace Cookbook\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRecipeRepository extends EntityRepository
{
    public function deleteCategoryRecipe($id)
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder()
            ->delete('Cookbook\CoreBundle\Entity\CategoryRecipe', 'i')
            ->where('i.id = :category_id')
            ->setParameter('category_id', $id)
            ->getQuery()
        ;
        return 1 === $q->getScalarResult();
    }
}