<?php

namespace Cookbook\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormatRecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatRecipeRepository extends EntityRepository
{
    public function deleteFormatRecipe($id)
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder()
            ->delete('Cookbook\CoreBundle\Entity\FormatRecipe', 'i')
            ->where('i.id = :format_id')
            ->setParameter('format_id', $id)
            ->getQuery()
        ;
        return 1 === $q->getScalarResult();
    }
}