<?php

namespace Cookbook\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
    public function deleteIngredient($id)
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder()
            ->delete('Cookbook\CoreBundle\Entity\Ingredient', 'i')
            ->where('i.id = :ingredient_id')
            ->setParameter('ingredient_id', $id)
            ->getQuery()
        ;
        return 1 === $q->getScalarResult();
    }
}