<?php

namespace Cookbook\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends EntityRepository
{
    public function getRecipe($param, $order)
    {
        $q = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('r')
            ->from('Cookbook\CoreBundle\Entity\Recipe','r')
            ->andWhere('r.people = :user_id')
            ->setParameter('user_id', $param['people'])
            ->orderBy('r.'.key($order),$order[key($order)]);
        $q2 = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('r2')
            ->from('Cookbook\CoreBundle\Entity\Recipe','r2')
            ->andWhere('r.people = :user_id')
            ->setParameter('user_id', $param['people']);
        
        if (isset($param['category'])) {
            $q->andWhere('r.category = :category_id')
            ->setParameter('category_id', $param['category']);
        }
        if (isset($param['format'])) {
            $q->andWhere('r.format = :format_id')
            ->setParameter('format_id', $param['format']);
        }
        if (isset($param['type'])) {
            $q->andWhere('r.type = :type_id')
            ->setParameter('type_id', $param['type']);
        }
        if (isset($param['personn'])) {
            foreach($param['personn'] as $personn) {
                if ($personn['personn'] != '') {
                    if ($personn['choix'] == 1) {
                        $q->innerJoin('r.events', 'e')
                            ->innerJoin('e.friends', 'p')
                            ->andWhere('p.id = :personn_id')
                            ->setParameter('personn_id', $personn['personn']);
                    }
                    else {
                        $q->andWhere(
                            $q->expr()->not(
                                $q->expr()->exists(
                                    $q2->innerJoin('r2.events', 'e')
                                        ->innerJoin('e.friends', 'p')
                                        ->andWhere('p.id = '.$personn['personn'])
                                        ->andWhere('r.id = r2.id')
                                        //->setParameter('personn2_id', $personn['personn'])
                                        ->getDQL()
                                )
                            )
                        );    
                    }
                }
            }
        }
        $select = $q->getQuery();
        return( $select->getResult());
    }
}