parameters:
#    cookbook_security.example.class: Cookbook\SecurityBundle\Example

services:
#    cookbook_security.example:
#        class: %cookbook_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
